import type { GameState } from "../core/types";

/** Process one week of sales for all active products. Returns revenue earned. */
export function processSales(state: GameState): number {
  let revenue = 0;
  for (const p of state.products) {
    if (!p.active) continue;
    const units = p.momentum;
    if (units < 5) {
      p.active = false;
      continue;
    }
    const rev = units * p.price;
    p.unitsSold += units;
    p.revenue += rev;
    revenue += rev;

    // fans trickle in from people enjoying good games
    state.fans += units * 0.012 * (p.reviewScore / 10);

    // decay momentum
    p.momentum *= 0.8;
  }
  return revenue;
}

/** Weekly salary expenses. */
export function weeklySalaries(state: GameState): number {
  return state.employees.reduce((s, e) => s + e.salary, 0);
}

/** Passive weekly research generated by the team. */
export function weeklyResearch(state: GameState): number {
  const tech = state.employees.reduce((s, e) => s + e.tech, 0);
  return tech * 0.06;
}
